{% set name = "pyubx2" %}
{% set version = "1.2.59" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyubx2-{{ version }}.tar.gz
  sha256: 4ea970af2aaa7984844f56016c15b86cc06e587305f36f4f8ae1ff7eed48ddb5
build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=75.0.0
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pynmeagps >=1.0.55
    - pyrtcm >=1.1.9

test:
  imports:
    - pyubx2
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/semuconsulting/pyubx2
  description: Python library for parsing and generating u-blox UBX GNSS protocol messages.
  summary: UBX protocol parser and generator
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://www.semuconsulting.com/pyubx2
  dev_url: https://github.com/semuconsulting/pyubx2

extra:
  recipe-maintainers:
    - semuadmin
